# Generated by Django 2.1.1 on 2018-09-26 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('all_rate', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specialty', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete='None', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
