# Generated by Django 2.1.1 on 2018-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conspectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conspect',
            name='all_rate',
        ),
        migrations.AddField(
            model_name='conspect',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
