# Generated by Django 2.1.1 on 2018-09-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conspectapp', '0002_auto_20180926_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
