# Generated by Django 2.1.1 on 2018-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conspectapp', '0003_auto_20180926_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspect',
            name='sum_all_vote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conspect',
            name='vote_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
