# Generated by Django 2.1.1 on 2018-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0002_remove_tag_conspects'),
        ('conspectapp', '0004_auto_20180930_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspect',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conspects', to='tagapp.Tag'),
        ),
    ]
