# Generated by Django 2.1.1 on 2018-10-10 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conspectapp', '0005_conspect_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspect',
            name='voted_user',
            field=models.ManyToManyField(blank=True, related_name='ratngs_conspects', to=settings.AUTH_USER_MODEL),
        ),
    ]
