# Generated by Django 2.1.1 on 2018-10-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conspectapp', '0006_conspect_voted_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conspect',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conspect',
            name='specialty',
        ),
    ]
