# Generated by Django 2.1.1 on 2018-10-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='conspects',
        ),
    ]
