# Generated by Django 2.1.1 on 2018-10-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0005_tag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
    ]
