# Generated by Django 2.1.1 on 2018-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conspectapp', '0003_auto_20180926_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('sum_all_vote', models.PositiveIntegerField()),
                ('vote_counter', models.PositiveIntegerField()),
                ('conspect', models.ForeignKey(on_delete=None, to='conspectapp.Conspect')),
            ],
        ),
    ]
