# Generated by Django 2.1.1 on 2018-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
