# Generated by Django 2.1.1 on 2018-09-30 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratingapp', '0002_auto_20180930_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
