# Generated by Django 2.1.1 on 2018-10-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0002_remove_photo_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
