# Generated by Django 2.1.1 on 2018-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fask',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
