# Generated by Django 2.1.1 on 2018-10-10 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='what_ask',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='what_is_response',
        ),
        migrations.AlterField(
            model_name='ask',
            name='who_ask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ask',
            name='who_is_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
