# Generated by Django 2.1.1 on 2018-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0005_ask_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
