# Generated by Django 2.1.1 on 2018-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absapp', '0003_auto_20180922_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
