# Generated by Django 2.1.1 on 2018-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absapp', '0004_abstract_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
