# Generated by Django 2.1.1 on 2018-09-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absapp', '0006_remove_abstract_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
