# Generated by Django 2.1.1 on 2018-09-23 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absapp', '0008_auto_20180922_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='author',
            field=models.ForeignKey(default=1, on_delete='None', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
