# Generated by Django 2.1.1 on 2018-09-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absapp', '0011_abstract_all_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='author',
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
    ]
