# Generated by Django 2.1.1 on 2018-09-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='conspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conspectapp.Conspect'),
        ),
    ]
