# Generated by Django 2.1.1 on 2018-10-08 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentapp', '0004_auto_20181001_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
