# Generated by Django 2.1.1 on 2018-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0005_coment_user_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
